"""modify list

Revision ID: 21391c0f7009
Revises: c9918df615cc
Create Date: 2024-11-20 14:00:16.475333

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '21391c0f7009'
down_revision = 'c9918df615cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('list', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('list', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###