"""remove family_id from task

Revision ID: 8b38707badd7
Revises: e5a4f4405eb7
Create Date: 2024-11-19 08:26:12.895852

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '8b38707badd7'
down_revision = 'e5a4f4405eb7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('task_family_id_fkey', 'task', type_='foreignkey')
    op.drop_column('task', 'family_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('family_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key('task_family_id_fkey', 'task', 'family', ['family_id'], ['id'])
    # ### end Alembic commands ###